version: '3'

networks:
  heimdall-network:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    privileged: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9091:9090'  # Changed port to avoid conflict
    networks:
      - heimdall-network

  blackbox:
    image: prom/blackbox-exporter:latest
    privileged: true
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - '9115:9115'
    networks:
      - heimdall-network

  node-exporter:
    image: prom/node-exporter:latest
    privileged: true
    ports:
      - '9101:9100'  # Changed port to avoid conflict
    networks:
      - heimdall-network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - heimdall-network

networks:
  heimdall-network:
    driver: bridge

